CREATE TABLESPACE TB_SPACE DATAFILE 'C:\app\oradata\orcl\SPACE_TBS.DBF' SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE USER robert IDENTIFIED BY qwerty
DEFAULT TABLESPACE TB_SPACE
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

GRANT CONNECT TO robert;
GRANT CREATE SESSION TO robert;
GRANT CREATE TABLE TO robert;
ALTER USER "ROBERT" QUOTA UNLIMITED ON TB_SPACE;
GRANT CREATE SEQUENCE TO robert;
GRANT CREATE PROCEDURE TO robert;
GRANT CREATE SYNONYM TO robert;
GRANT CREATE MATERIALIZED VIEW TO robert;
GRANT CREATE VIEW TO robert;
GRANT ON COMMIT REFRESH TO robert;
